[package]
name = "bagels-with-vector"
version = "0.1.0"
authors = ["Henry Chen <chenx97@aosc.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
